image: "python:3.6-buster"

stages:
  - test

before_script:
  - apt-get update -qy
  - pip3 install .[testing]

test main:
  stage: test
  script:
    - coverage run -m unittest discover
    - coverage report

test 3.7:
  stage: test
  image: "python:3.7-slim-buster"
  script:
    - python3 -m unittest discover

test 3.8:
  stage: test
  image: "python:3.8-slim-buster"
  script:
    - python3 -m unittest discover